definitions: {}
info:
  description: powered by Flasgger
  termsOfService: /tos
  title: A swagger API
  version: 0.0.1
paths:
  /contacts:
    post:
      parameters:
      - in: body
        name: body
        required: true
        schema:
          properties:
            name:
              type: string
            phone:
              type: string
          required:
          - name
          - phone
          type: object
      responses:
        '201':
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u0441\u043E\u0437\
            \u0434\u0430\u043D"
          schema:
            properties:
              id:
                type: integer
              name:
                type: string
              phone:
                type: string
            type: object
      tags:
      - Contacts
  /contacts/{contact_id}:
    delete:
      parameters:
      - description: "\u0418\u0434\u0435\u043D\u0442\u0438\u0444\u0438\u043A\u0430\
          \u0442\u043E\u0440 \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u0430"
        in: path
        name: contact_id
        required: true
        type: integer
      responses:
        '200':
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u0443\u0434\u0430\
            \u043B\u0451\u043D"
        '404':
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u043D\u0435 \u043D\
            \u0430\u0439\u0434\u0435\u043D"
      tags:
      - Contacts
    get:
      responses:
        '200':
          description: "\u0418\u043D\u0444\u043E\u0440\u043C\u0430\u0446\u0438\u044F\
            \ \u043E \u043A\u043E\u043D\u0442\u0430\u043A\u0442\u0435"
          schema:
            properties:
              id:
                type: integer
              name:
                type: string
              phone:
                type: string
            type: object
        '404':
          description: "\u041A\u043E\u043D\u0442\u0430\u043A\u0442 \u043D\u0435 \u043D\
            \u0430\u0439\u0434\u0435\u043D"
      tags:
      - Contacts
swagger: '2.0'
